"""add industry country city state to contacts

Revision ID: b269f2a46216
Revises: 003_add_api_keys
Create Date: 2026-01-31 00:21:07.176783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b269f2a46216'
down_revision: Union[str, None] = '003_add_api_keys'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_api_keys_active'), table_name='api_keys')
    op.drop_index(op.f('idx_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('idx_api_keys_user_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.add_column('contacts', sa.Column('industry', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('country', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('city', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('state', sa.Text(), nullable=True))
    op.drop_index(op.f('idx_contacts_email_unique'), table_name='contacts', postgresql_where='((email IS NOT NULL) AND (deleted_at IS NULL))')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_contacts_email_unique'), 'contacts', ['email'], unique=True, postgresql_where='((email IS NOT NULL) AND (deleted_at IS NULL))')
    op.drop_column('contacts', 'state')
    op.drop_column('contacts', 'city')
    op.drop_column('contacts', 'country')
    op.drop_column('contacts', 'industry')
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('key_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('key_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('access_level', postgresql.ENUM('read', 'write', 'admin', name='access_level'), server_default=sa.text("'read'::access_level"), autoincrement=False, nullable=False),
    sa.Column('rate_limit', sa.INTEGER(), server_default=sa.text('1000'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('api_keys_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('api_keys_pkey'))
    )
    op.create_index(op.f('idx_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_index(op.f('idx_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('idx_api_keys_active'), 'api_keys', ['is_active'], unique=False)
    # ### end Alembic commands ###
