"""Add unique constraint to contacts email

Revision ID: f51fa7fc59ca
Revises: b269f2a46216
Create Date: 2026-01-31 01:05:04.963149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51fa7fc59ca'
down_revision: Union[str, None] = 'b269f2a46216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_contacts_email'), table_name='contacts')
    op.create_index('idx_contacts_email', 'contacts', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_contacts_email', table_name='contacts')
    op.create_index(op.f('idx_contacts_email'), 'contacts', ['email'], unique=False)
    # ### end Alembic commands ###
